# Generated by Django 5.2.11 on 2026-02-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aipastorapp', '0002_rename_sent_at_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=20)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'bible_verses',
                'indexes': [models.Index(fields=['content'], name='bible_verse_content_561b44_idx')],
            },
        ),
    ]
