"""
Django settings for aipastorproject project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

import environ
import os
from pathlib import Path

# 1. 환경 변수 설정 및 로드
# BASE_DIR은 프로젝트 최상위 폴더(manage.py가 있는 곳)를 가리킵니다.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # DEBUG의 기본값은 False로 설정 (보안)
    DEBUG=(bool, False)
)

# .env 파일을 읽어옵니다.
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# 2. 보안 및 핵심 설정 (.env에서 호출)
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')

# 포트폴리오 확인 및 로컬 테스트를 위해 모든 호스트 허용
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aipastorapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aipastorproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'aipastorapp' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aipastorproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# 모든 민감 정보는 .env 파일에서 가져옵니다.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# 정적 파일이 저장된 폴더 등록
STATICFILES_DIRS = [
    BASE_DIR / 'aipastorapp' / 'static',
]

# 로그인/로그아웃 관련 설정
LOGIN_REDIRECT_URL = 'main_page'
LOGOUT_REDIRECT_URL = 'login'

# 보안 설정 (세션 관리)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800  # 30분 후 자동 로그아웃
SESSION_SAVE_EVERY_REQUEST = True

# 모델 기본 ID 필드 설정
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'